# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='masuk',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='user',
            new_name='name',
        ),
    ]
