# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180703_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lat', models.CharField(max_length=40)),
                ('lng', models.CharField(max_length=40)),
                ('address', models.TextField()),
            ],
        ),
    ]
