# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='siapsat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satuan', models.CharField(max_length=100)),
                ('posisi', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('kotama', models.CharField(max_length=100)),
            ],
        ),
    ]
