# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ekko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('personnel_quanlity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('personnel_mantap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('personnel_status', models.CharField(max_length=20)),
                ('materiil_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('materiil_quality', models.DecimalField(decimal_places=2, max_digits=5)),
                ('materiil_mantap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('materiil_status', models.CharField(max_length=20)),
                ('exercise_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_quality', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_mantap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise_status', models.CharField(max_length=20)),
                ('pangkalan_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pangkalan_quality', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pangkalan_mantap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pangkalan_status', models.CharField(max_length=20)),
                ('penak_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('penak_quality', models.DecimalField(decimal_places=2, max_digits=5)),
                ('penak_mantap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('penak_status', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quality', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mantap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=20)),
                ('induk', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periode', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.DecimalField(decimal_places=2, max_digits=5)),
                ('satuan_id', models.CharField(max_length=20)),
            ],
        ),
    ]
