# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_ekko'),
    ]

    operations = [
        migrations.CreateModel(
            name='geojson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('satuan_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='exercise_mantap',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='exercise_quality',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='exercise_quantity',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='exercise_status',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='induk',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='materiil_mantap',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='materiil_quality',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='materiil_quantity',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='materiil_status',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='pangkalan_mantap',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='pangkalan_quality',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='pangkalan_quantity',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='pangkalan_status',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='penak_mantap',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='penak_quality',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='penak_quantity',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='penak_status',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='periode',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='personnel_mantap',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='personnel_quanlity',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='personnel_quantity',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='personnel_status',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='year',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='combat_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_induk',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_rahwan',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='level_0_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='priority_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='vice_leader',
        ),
        migrations.AlterField(
            model_name='ekko',
            name='satuan_id',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='geojson',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.organization'),
        ),
    ]
